### ISSUE TITLE
relocatable package few .jar files are wrong in the root of the tarball

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-tools-java#104]
those files:
```
apache-cassandra-666.development-20190501.15c65577c5.jar        
apache-cassandra-thrift-666.development-20190501.15c65577c5.jar 
scylla-tools-666.development-20190501.15c65577c5.jar
```
are on the root of the tarball, should they be inside of /lib directory are the rest of the files ?

**Comment by glommer** [comment]
https://github.com/scylladb/scylla-tools-java/commit/1b74d28ecb3929d5bb8a7aaa7b75df68b935bd08

**Comment by fruch** [comment]
@glommer that mean it's merged into somewhere ? i.e. master/next/enterprise ?

**Comment by glommer** [comment]
Yes it should be merged into master.
If this is a nice to have future fix, then we wait.

If this is blocking anything in a released version, then we request a
backport.

I didn't request a backport when I wrote it because I did not see the need
for it

**Comment by fruch** [comment]
o.k. its not a bit deal, just extra copy step in CCM to get thong working, I guess it gonna be left there anyhow for  supporting older relocatables

**Comment by fruch** [comment]
I've check a recent relocatable from master, and all jar files are in place
