### ISSUE TITLE
sstableloader ignores range tombstones that signify ranges

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-tools-java#12]
sstableloader assumes that a range tombstone signifies a clustering row prefix, but that is not always the case.

For example, with

```
CREATE TABLE tab (
    pk int,
    a int,
    b int,
    v int,
    PRIMARY KEY (pk, a, b)
);

DELETE FROM tab WHERE pk = 1 AND a = 3;
DELETE FROM tab WHERE pk = 1 AND a = 3 AND b = 4;
```

we get three range tombstones, two of which are really ranges:

```
[(3), (3, 4))
[(3, 4), (3, 4)]
((3, 4), (3)]
```

**Comment by penberg** [comment]
@avikivity @elcallio Is this still an open issue?

**Comment by slivne** [comment]
@elcallio - can we close this ?

**Comment by elcallio** [comment]
Afaict.
