### ISSUE TITLE
cqlsh: lack of support in duplicate columns

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-tools-java#129]
This is a mirror of [CASSANDRA-13262](https://issues.apache.org/jira/browse/CASSANDRA-13262)
This is a cqlsh problem that have been fixed in upstream cassandra 3.11.4.
We will need to merge from upstream to get the fix.

**Comment by avelanarius** [comment]
We did eventually merge upstream Cassandra 3.11.4 that contained the fix. I confirmed manually that `cqlsh` now correctly displays duplicate columns. A search through the repo says that Scylla `2.3.rc3` was the first Scylla with this fix.
