### ISSUE TITLE
3.2.0 does ship with CVE yaml.load

### ISSUE THREAD

**Issue by ultrabug** [scylladb/scylla-tools-java#139]
Hello

Can we please get the CVE fix of yaml.load into 3.2.x releases? it's sad to see it's not made it since 2 months :(

https://github.com/scylladb/scylla-tools-java/commit/35906df2a0d1b94ab0df095dffd7f8c4ecf33e3a

Thanks

**Comment by penberg** [comment]
Commit 35906df is backported to 3.1 and 3.2 now. Thanks, @ultrabug!

**Comment by ultrabug** [comment]
Great @penberg cheers!
