### ISSUE TITLE
sstable metadata: weird output for KA, LA sstables

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla-tools-java#149]
sstable metadata was updated to include fields from MC format only, the problem is that the tool is not aware of that and print fields that dont exist in KA, LA sstables.

example of sstable metadata output on a KA sstable:
TTL min: 0
TTL max: 2147483647
Estimated droppable tombstones: 0.6042750929368029
SSTable Level: 0
Repaired at: 0
Replay positions covered: {CommitLogPosition(segmentId=-1, position=0)=CommitLogPosition(segmentId=0, position=0)}
totalColumnsSet: -1
totalRows: -1

min_local_deletion_time, min and max ttl, columns_count and rows_count should be excluded from the output if sstable version is KA / LA.

**Comment by vladzcloudius** [comment]
@slivne @eyalgutkind 
Please, prioritize this. 
This is a users impacting fix.

**Comment by eliransin** [comment]
@raphaelsc your example is cut off - here is a full output, can you please mark for each field
for which table format is it relevant?:
```
Partitioner: org.apache.cassandra.dht.Murmur3Partitioner
Bloom Filter FP chance: 0.010000
Minimum timestamp: 1589096539136563
Maximum timestamp: 1589096539136563
SSTable min local deletion time: 2147483647
SSTable max local deletion time: 2147483647
Compressor: org.apache.cassandra.io.compress.LZ4Compressor
Compression ratio: NaN
TTL min: 0
TTL max: 2147483647
Estimated droppable tombstones: 0.0
SSTable Level: 0
Repaired at: 0
Replay positions covered: {CommitLogPosition(segmentId=-1, position=0)=CommitLogPosition(segmentId=198158383985722307, position=4115)}
totalColumnsSet: -1
totalRows: -1
Estimated tombstone drop times:
Count               Row Size        Cell Count
1                          0                 0
2                          0                 0
3                          0                 0
...
Estimated cardinality: 1
```

**Comment by eliransin** [comment]
@raphaelsc ping, please mark the fields that are mc specific so I can implement.

**Comment by raphaelsc** [comment]
SSTable min local deletion time, totalColumnsSet, TTL min, TTL max, totalColumnsSet, totalRows

All those should be excluded if SSTable version is ka/la

**Comment by bhalevy** [comment]
@scylladb/scylla-tools-maint 

Needs to be backported to 4.1 and 4.0
and to enterprise 2019.1 and 2020.1
See https://github.com/scylladb/scylla-enterprise/issues/1297

**Comment by avikivity** [comment]
Backported to 4.0, 4.1. 4.2 already has this.
