### ISSUE TITLE
via cqlsh not possible to escape special characters such as ' when used as FILTER for UPDATE

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-tools-java#150]
This is a copy of scylladb/scylla#6165

Summary of the problem is that in certain situations a pg style string that
contains single quotation mark is miss parsed in cqlsh and causes it to wait for more
input, the example in the issue was:
`UPDATE pi.upui SET createddate='1974-10-17 00:00:00.00+0000' WHERE upuishort=$$uyuyueyy'euyruwey$$;`

For more details refer to  scylladb/scylla#6165

**Comment by vladzcloudius** [comment]
@slivne @avikivity Could you, please, give me "labelling" permissions for this repo?
