### ISSUE TITLE
fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-tools-java#16]
The package now requires Java 8, but 14.04 only supplies Java 8.

I found a jdk 8 repo [here](http://askubuntu.com/questions/464755/how-to-install-openjdk-8-on-14-04-lts).

**Comment by slivne** [comment]
we need one for debian 8 as well

**Comment by avikivity** [comment]
I was able to install on debian 8 with this:


echo 'deb http://ftp.de.debian.org/debian jessie-backports main' > 
/etc/apt/sources.list.d/jessie-backports.list
apt update
apt install -t jessie-backports  openjdk-8-jdk-headless
