### ISSUE TITLE
scylla-sstableloader gives Cannot generate <> comparison for primary key colum ColumnDefinition{name=h, type=org.apache.cassandra.db.marshal.Int32Type, kind=CLUSTERING, position=0}

### ISSUE THREAD

**Issue by pidiaquez** [scylladb/scylla-tools-java#207]
Component: scylla-sstableloader

version:  scylla-enterprise-tools-core-2018.1.14-0.20190807.0cabdff9a4.el7.noarch

used lo load a table with 500G , jus 1 table ( DDL below )

data is coming from a snapshot taken from the same node.

just 1 table being loaded.  KS=phoenix_v3  table  [tenant_tag_data_points]

`CREATE TABLE phoenix_v3.tenant_tag_data_points (
tnt text,
thsh text,
l int,
ahsh text,
v int,
h int,
a text static,
d boolean,
g blob,
q tinyint,
t text static,
y tinyint,
PRIMARY KEY ((tnt, thsh, l, ahsh, v), h)
) WITH CLUSTERING ORDER BY (h ASC)`

after scylla-sstableloader works loading records for 2h is finish with exception  

`java.lang.IllegalStateException: Cannot generate <> comparison for primary key colum ColumnDefinition{name=h, type=org.apache.cassandra.db.marshal.Int32Type, kind=CLUSTERING, position=0}
at com.scylladb.tools.SSTableToCQL$RowBuilder.setWhere(SSTableToCQL.java:335)
at com.scylladb.tools.SSTableToCQL$RowBuilder.deleteCqlRow(SSTableToCQL.java:382)
at com.scylladb.tools.SSTableToCQL$RowBuilder.process(SSTableToCQL.java:728)
at com.scylladb.tools.SSTableToCQL$RowBuilder.process(SSTableToCQL.java:694)
at com.scylladb.tools.SSTableToCQL$RowBuilder.access$200(SSTableToCQL.java:109)
at com.scylladb.tools.SSTableToCQL.process(SSTableToCQL.java:900)
at com.scylladb.tools.SSTableToCQL.stream(SSTableToCQL.java:931)
at com.scylladb.tools.BulkLoader.main(BulkLoader.java:1026)`

this exception comes from

**./java/com/scylladb/tools/SSTableToCQL.java**

error always references column name=h  which match the Clustering Key.

can this be due to data out of band ? or what can be triggering this exception?

Thanks

**Comment by penberg** [comment]
@elcallio @haaawk, I think this is for you.

**Comment by elcallio** [comment]
Already fixed in master. See https://github.com/scylladb/scylla-tools-java/commit/2d49ded77b7dea47543b60e19d83f7e3362cfc4d#diff-9ee7b29929414174de8ca2181cf9f18c

**Comment by nyh** [comment]
@pidiaquez @elcallio if this is already fixed, can we close this issue?

**Comment by elcallio** [comment]
Yes.
