### ISSUE TITLE
cassandra.in.sh shouldn't print debug prints into stdout

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-tools-java#213]
like here:
https://github.com/scylladb/scylla-tools-java/blob/3eca0e35111f48629cf5b654dd5212199029f78e/tools/bin/cassandra.in.sh#L63

this shouldn't be part of the stdout, for example in tools like sstabledump, it would break some tools and automation with this outout

**Comment by penberg** [comment]
@fruch What debug printouts are you referring to? That `echo` will be printed to `stdout` unless something explicitly redirected it...

/cc @elcallio

**Comment by fruch** [comment]
> @fruch What debug printouts are you referring to? That `echo` will be printed to `stdout` unless something explicitly redirected it...
> 
> /cc @elcallio

And that's exactly the problem (my the title was backwards...), when using tools like `sstabledump` this print is messing the output. i.e. if someone had automation ontop of it (i.e. dtest has one), it breaks by this print

this should go to stderr, if we must have it

**Comment by tarzanek** [comment]
FWIW
this wasn't present in 2020.1.0 and also previous OSS versions ...
so from my point of view this is a regression (caused either by some ENV change or script change)
@elcallio @syuu1228

**Comment by tarzanek** [comment]
sorry, correcting people in above message,
Julius I think this is your bug/regression - @jul-stas https://github.com/scylladb/scylla-tools-java/commit/3eca0e35111f48629cf5b654dd5212199029f78e

**Comment by tarzanek** [comment]
btw. I agree with removing this message, or at least sending to stderr
(if my vote matters :-) )
(and definitely release notes should cover it, people tend to use nodetool outputs in automation and this breaks all of them!)

**Comment by fruch** [comment]
> btw. I agree with removing this message, or at least sending to stderr
> (if my vote matters :-) )
> (and definitely release notes should cover it, people tend to use nodetool outputs in automation and this breaks all of them!)

this is exactly why I've raised it, the line to all the places in the CCM/dtest code that we need to adapt for it.
for "reasons" we aren't covering it in dtest today (since it's not using this file, it's using it's own environment variables), and we don't use all the tools in other places, it whet under the radar. 

And I'm sure it would break users automation code (as it broken some of ours)
