### ISSUE TITLE
sstableloader: column names are escaped twice

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla-tools-java#220]
This causes double double quotes when we have a column name with capitals. I.e. column 'C0' becomes '""C0""' instead of '"C0"'.

The root is that column name mapping and case sensitivity handling seem to have gotten added across each other, Since the former actually uses cassandra internal interning of names, we should not do additional quote-wrapping after this.

**Comment by nyh** [comment]
This issue became even more important when it caused a failure of sstableloader for a potential Alternator client: Alternator has a column named :attr (with a colon), and sstableloader used two quotes to quote its name.
So let's get the PR for this issue reviewed and committed.
