### ISSUE TITLE
nodetool removenode doesn't support "--ignore-dead-nodes" option

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-tools-java#225]
`--ignore-dead-nodes` option was added to 'removenode` in https://github.com/scylladb/scylla/pull/7626 and works via API, but it wasn't enabled in nodetool

**Comment by juliayakovlev** [comment]
@slivne  @asias

**Comment by asias** [comment]
can we close https://github.com/scylladb/scylla-tools-java/issues/251 now?

**Comment by bhalevy** [comment]
@avikivity @roydahan @denesb: should we backport 8fae618f7ffdbaf9f71bea93005ed2225c2c2bbe to 4.6?
(Or we can fork branch-4.6 from this change or maybe even from current master and update the scylla submodule)

**Comment by bhalevy** [comment]
FWIW dtests in 4.6 are expecting this option to work there, and I think it's required regardless.

https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/dtest-release-pytest/75/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/test_simple_removenode_3_nodetool_True_/:
```
E               ccmlib.node.NodetoolError: Nodetool command '/jenkins/workspace/scylla-4.6/dtest-release-pytest/scylla/.ccm/scylla-repository/2f2d22a8641a029ba34cb030e189085c820f4ee8/scylla-tools-java/bin/nodetool -h 127.0.71.1 -p 7171 removenode --ignore-dead-nodes 127.0.71.5,127.0.71.4 6baf2db8-f9fe-4474-a336-201bce45bd68' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP POST to URL '/storage_service/remove_node' failed: std::runtime_error (removenode[6909e58d-7664-493c-b87b-36079691b915]: Nodes={127.0.71.4, 127.0.71.5} needed for removenode operation are down. It is highly recommended to fix the down nodes and try again. To proceed with best-effort mode which might cause data inconsistency, run nodetool removenode --ignore-dead-nodes <list_of_dead_nodes> <host_id>. E.g., nodetool removenode --ignore-dead-nodes 127.0.0.1,127.0.0.2 817e9515-316f-4fe3-aaab-b00d6f12dddd)
```
