### ISSUE TITLE
resetlocalschema is not enabled in nodetool

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-tools-java#226]
Need to enable `resetlocalschema`

**Comment by juliayakovlev** [comment]
@tgrabiec Is this fix should be backported to 4.4? This feature is part of 4.4 AFAIK

@penberg

**Comment by tgrabiec** [comment]
@juliayakovlev No need to backport IMO

**Comment by juliayakovlev** [comment]
@tgrabiec your commit https://github.com/scylladb/scylla/commit/d3a5814f4fd0ef80f3dbfde4095eb11feb05745a was backported to 4.4. So we need this fix there also I think

**Comment by tgrabiec** [comment]
It's fine to have a RESTful API without the nodetool part.
