### ISSUE TITLE
sstableloader: batches with column names that contain ':' character are created incorrectly

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-tools-java#230]
When copying correct sstables generated by Alternator, sstableloader doesn't work without `-nb` option which disables using batch statements **if `-nx` option, which disables prepared statements, is also present**. The reason is that alternator tables usually contain a column with very specific name: `:attrs`. This column confuses sstableloader, which probably thinks it's a named marker, and replaces the column name with a CQL wildcard (`?`).

Here's how a generated batch statement looks like:
```cql
INSERT INTO "alternator_ks"."test" (p,c) values (?,?) USING TIMESTAMP 1614933647548014;
UPDATE "alternator_ks"."test" USING TIMESTAMP 1614933643936873 SET "?"[?] = ? WHERE p = ? AND c = ?;
```
and here's how it should look like:
```cql
INSERT INTO "alternator_ks"."test" (p,c) values (?,?) USING TIMESTAMP 1614933647548014;
UPDATE "alternator_ks"."test" USING TIMESTAMP 1614933643936873 SET ":attrs"[?] = ? WHERE p = ? AND c = ?;
```

**Comment by psarna** [comment]
Discovered when verifying #221

**Comment by nyh** [comment]
Note that this bug may be specific to the case of a map column as in the broken example shown above. @Orenef11 reported that he tried an integer column name beginning with a colon and didn't have any problems.

**Comment by psarna** [comment]
Important note: I just updated this issue's description: this bug only manifests if `-nx` flag is present. `-nx` disables prepared statements, so it's generally not a good idea to use it, but it should nonetheless work fine.

**Comment by nyh** [comment]
> Important note: I just updated this issue's description: this bug only manifests if `-nx` flag is present. `-nx` disables prepared statements, so it's generally not a good idea to use it, but it should nonetheless work fine.

Can you please look again at the sentence you wrote in the issue description? You wrote 'sstableloader only works fine with -nb option ... if -nx option ... is also present.' - is this correct? This doesn't sound right - I thought you said the bug exhibits if "-nx" is present - not that it works fine if it's present...

**Comment by psarna** [comment]
Yes, too many negations in a single sentence got me confused. Updated, thanks

**Comment by nyh** [comment]
Thanks @psarna.
@Orenef11 can you please add to your dtest which tests Alternator+sstableloader, which already has two runs - one without parameters and one with "-nb", also a third run with "-nx"? This third run should fail on this issue, and get fixed by Calle's patch when we commit it.

**Comment by Orenef11** [comment]
> Thanks @psarna.
> @Orenef11 can you please add to your dtest which tests Alternator+sstableloader, which already has two runs - one without parameters and one with "-nb", also a third run with "-nx"? This third run should fail on this issue, and get fixed by Calle's patch when we commit it.

NP, Ill add it.

**Comment by Orenef11** [comment]
> Thanks @psarna.
> @Orenef11 can you please add to your dtest which tests Alternator+sstableloader, which already has two runs - one without parameters and one with "-nb", also a third run with "-nx"? This third run should fail on this issue, and get fixed by Calle's patch when we commit it.

The test that runs `sstableloader` with flag `nx` is failed.
Can I reopen this bug?

**Comment by Orenef11** [comment]
> > Thanks @psarna.
> > @Orenef11 can you please add to your dtest which tests Alternator+sstableloader, which already has two runs - one without parameters and one with "-nb", also a third run with "-nx"? This third run should fail on this issue, and get fixed by Calle's patch when we commit it.
> 
> The test that runs `sstableloader` with flag `nx` is failed.
> Can I reopen this bug?

I checked it for the last Scylla version (`master_2021-04-06T22_36_26Z`) and the test is passed
