### ISSUE TITLE
Support load and stream feature in nodetool

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-tools-java#253]
In scylla commit 4d32d0317248d7c84ba91a16bc3252b2c8d98428 (storage_service: Introduce load_and_stream), the load and stream feature was implemented. 

We need to add the load and stream feature to nodetool to make it is easier for users to use, e.g., 

nodetool  refresh  --load-and-stream -- myks mytable

A load_and_stream parameter is added to the REST api to turn on the feature.

curl -X POST "http://{ip}:10000/storage_service/sstables/{keyspace}?cf={table}&load_and_stream=true

**Comment by bhalevy** [comment]
@slivne / @haaawk / @penberg who's responsible for implementing these features?

**Comment by haaawk** [comment]
I think @jul-stas could help. He has some experience with nodetool commands. @jul-stas would you help @bhalevy ?

**Comment by jul-stas** [comment]
Will do, I just have some open tasks to finish first.
