### ISSUE TITLE
NullPointerException related to opts.maxPendingPerConnection in tools/stress: 

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-tools-java#257]
With 6fa38389320661e10c34d03daf328c9d8b5f3445 we see the following error with multiple dtests on scylla/next:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3598/testReport/bootstrap_test/TestBootstrap/dtest___manual_bootstrap_test/
```
Stress command exited with error code: 1
stdout: 
stderr: java.lang.NullPointerException
	at org.apache.cassandra.stress.settings.SettingsMode.<init>(SettingsMode.java:68)
	at org.apache.cassandra.stress.settings.SettingsMode.get(SettingsMode.java:235)
	at org.apache.cassandra.stress.settings.StressSettings.get(StressSettings.java:276)
	at org.apache.cassandra.stress.settings.StressSettings.parse(StressSettings.java:241)
	at org.apache.cassandra.stress.Stress.run(Stress.java:80)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```

https://github.com/scylladb/scylla-tools-java/blob/6fa38389320661e10c34d03daf328c9d8b5f3445/tools/stress/src/org/apache/cassandra/stress/settings/SettingsMode.java#L68

Does it translate to `Integer.valueOf(null)`?

**Comment by nyh** [comment]
@bhalevy @avikivity it's Sunday so @haaawk shouldn't be fixing this today. We haven't had a next promotion in 6 days. Maybe we should revert this patch **now** and have him create a different patch (e.g., use maxint instead of "null") later?

According to the commit's message, it was needed to fix longevity tests, not dtests, so reverting it can help to restore dtest success.

**Comment by avikivity** [comment]
I dropped the tools/java submodule update that brought this in.

**Comment by nyh** [comment]
> I dropped the tools/java submodule update that brought this in.

Thanks. We need to remember that since you just dropped the submodule update (not reverted the patch inside the submodule), then if we `refresh-submodules.sh` again we'll get this breaking change again. So we musn't forget to fix this issue soon.

**Comment by haaawk** [comment]
I'm working on the fix now. Should have a PR in an hour or so. Sorry about that.

**Comment by haaawk** [comment]
The fix is here: https://github.com/scylladb/scylla-tools-java/pull/258
