### ISSUE TITLE
Nodetool refresh --load-and-stream doesn't support --primary-replica-only

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-tools-java#282]
Nodetool refresh now supports `--load-and-stream` (commit https://github.com/scylladb/scylla/commit/1b75e9312dd301e3f3ef99409107c53eac29b665, fixes the issue https://github.com/scylladb/scylla-tools-java/issues/253).

`load-and stream` feature has additional paramener: `--primary-replica-only`. See https://github.com/scylladb/scylla/commit/df3ef800c20c60d7929ffa600649793aa6c73064#:~:text=%22name%22%3A%22primary_replica_only%22%2C.

API supports it, but nodetool does not support. Fails with:

```
nodetool -h 127.0.95.1 -p 7195 refresh --load-and-stream -- keyspace1 standard1 --primary-replica-only true' failed; exit status: 1; stdout: nodetool: refresh requires ks and cf args
```

Same error if `--primary-replica-only` is false.

**Comment by tzach** [comment]
Load and stream is already documented  
https://docs.scylladb.com/operating-scylla/nodetool-commands/refresh/#load-and-stream

**Comment by juliayakovlev** [comment]
> Load and stream is already documented https://docs.scylladb.com/operating-scylla/nodetool-commands/refresh/#load-and-stream

Tes, but `--primary-replica-only` is missed.
There is the issue about this (see descriotion). When the issue will be fixed, we need to add description of `--primary-replica-only` parameter.
I opened this issue as reminder

**Comment by slivne** [comment]
@asias did you add support in nodetool - if so can you please fix the above issue as well

**Comment by slivne** [comment]
@eliransin ping

**Comment by slivne** [comment]
@eliransin / @asias ping

**Comment by tzach** [comment]
@eliransin / @asias can you please take a look

**Comment by asias** [comment]
The `--primary-replica-only` option is not a must to use load and stream feature. It is used only by an advanced procedure which needs cluster wide repair after load and stream. Let's not expose --primary-replica-only to nodetool now.

**Comment by mykaul** [comment]
> The `--primary-replica-only` option is not a must to use load and stream feature. It is used only by an advanced procedure which needs cluster wide repair after load and stream. Let's not expose --primary-replica-only to nodetool now.

@eliransin - please prioritize (or de-prioritize) this one. It also appears in 5.1's release notes (https://groups.google.com/g/scylladb-users/c/8ZuF1JkuDjg/m/qwUkwy_mAQAJ ) so let's consider the overall impact.

**Comment by tzach** [comment]
Can we please fix this? its pending the load and stream feature for almost a year now

**Comment by asias** [comment]
> Can we please fix this? its pending the load and stream feature for almost a year now

@tzach Why does this option prevents the feature at all? See my comments here: https://github.com/scylladb/scylla-tools-java/issues/282#issuecomment-1250668946

**Comment by tzach** [comment]
Its does not
We will release the feature without it, and a not so great UX.

**Comment by tzach** [comment]
@mykaul can we fix this issue?
Seem like a minor fix, and is pending for many months now.

**Comment by mykaul** [comment]
@eliransin ?

**Comment by asias** [comment]
> @eliransin ?

Since nobody is picking this up, I will work on this.

**Comment by asias** [comment]
The PR is here:

https://github.com/scylladb/scylla-tools-java/pull/327
https://github.com/scylladb/scylla-jmx/pull/192
