### ISSUE TITLE
scylla java tools do not recognize the "me" format

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-tools-java#291]
See https://github.com/scylladb/scylla-dtest/issues/2616
for such a failiure

**Comment by bhalevy** [comment]
Cc @raphaelsc

**Comment by raphaelsc** [comment]
$ ./tools/bin/sstablemetadata ~/tmp/1/keyspace1/standard1-e34e9e308ec311ecb74cf1dd6a966d09/me-284-big-Statistics.db 
Exception in thread "main" java.security.InvalidParameterException: SSTable Format: 'me' is unsupported.
	at org.apache.cassandra.tools.SSTableMetadataViewer$SSTableFormat.fromString(SSTableMetadataViewer.java:85)
	at org.apache.cassandra.tools.SSTableMetadataViewer.main(SSTableMetadataViewer.java:166)

**Comment by raphaelsc** [comment]
SSTable metadata fails for the new me format.

**Comment by bhalevy** [comment]
Cc @haaawk @cmm

**Comment by cmm** [comment]
(assuming people are looking at me)
1. what's the expected thing to be done here, "just" merge C* 3.11.12 (first merge in 3 years, looks fun)?  something else?
2. how does one properly test the result?

**Comment by bhalevy** [comment]
> (assuming people are looking at me)
> 
> 1. what's the expected thing to be done here, "just" merge C* 3.11.12 (first merge in 3 years, looks fun)?  something else?

I think that would be best.

@haaawk / @amnonh what do you think?

> 2. how does one properly test the result?

Our dtests make use and test the tools.
If you update the tools/java submodule in scylla with your change
and build the tools in your tree (`ninja dist-{tools,jmx}`)
you can test them locally with dtest.

Besides the test failure that drove this issue:
compaction_additional_test.py::TestTimeWindowDataSegregation::test_twcs_multiple_sstables_during_decommission
I suggest testing nodetool_additional_test.py

**Comment by denesb** [comment]
> $ ./tools/bin/sstablemetadata ~/tmp/1/keyspace1/standard1-e34e9e308ec311ecb74cf1dd6a966d09/me-284-big-Statistics.db

We should look into replacing these usages with `scylla sstable`. I will look into that.

**Comment by denesb** [comment]
> > $ ./tools/bin/sstablemetadata ~/tmp/1/keyspace1/standard1-e34e9e308ec311ecb74cf1dd6a966d09/me-284-big-Statistics.db
> 
> We should look into replacing these usages with `scylla sstable`. I will look into that.

Needs https://github.com/scylladb/scylla/issues/10126.

**Comment by bhalevy** [comment]
Similar problem in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1130/testReport/offline_tools_test/TestOfflineTools/test_sstablelevelreset/

```
self = <offline_tools_test.TestOfflineTools object at 0x7fa02878cb50>
data = [('', 'Exception in thread "main" java.security.InvalidParameterException: SSTable Format: \'me\' is unsupported.\n\ta...iewer.java:85)\n\tat org.apache.cassandra.tools.SSTableMetadataViewer.main(SSTableMetadataViewer.java:166)\n', 1), ...]

    def get_levels(self, data):
        levels = []
        for sstable in data:
            (metadata, error, rc) = sstable
>           level = int(re.findall("SSTable Level: [0-9]", metadata)[0][-1])
E           IndexError: list index out of range

offline_tools_test.py:121: IndexError
```

**Comment by bhalevy** [comment]
Reopening based on https://github.com/scylladb/scylla-tools-java/pull/292#issuecomment-1077764828

@avikivity I understand from @cmm this could just have been a pilot error.
He reports that the build succeeds for him on a clean build (after `rm -rf tools/java/build`)
