### ISSUE TITLE
nodetool compactstats: wrong statistics

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla-tools-java#30]
After re-starting node the nodetool compactstats seems to be 'stuck' on pending tasks:
nodetool -h 127.0.0.1 -p 7100 compactionstats -H
pending tasks: 2

**Comment by larisau** [comment]
the same test running on monster with 8 shards:
dtest: DEBUG: pending tasks: 0
       id   compaction type    keyspace       table   completed   total   unit   progress
   <none>        COMPACTION   keyspace1   standard1        2615   31104   keys      8.41%
Active compaction remaining time :   0h00m00s

**Comment by slivne** [comment]
@larisau - just to clarify - the resharding here - is due to the change of the msb_bits conf not because of changing the number of cores.

**Comment by DoronArazii** [comment]
Closing.
Please re-open if it's still relevant.
