### ISSUE TITLE
Support SNI proxy in cqlsh

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-tools-java#317]
We need `cqlsh` to support connections through SNI proxy and to read the connection config file. The relevant driver change is https://github.com/scylladb/python-driver/pull/159.

**Comment by Lorak-mmk** [comment]
Created PRs with required chagnes:
- another PR to Python Driver (previous one didn't catch all incompatibilites): https://github.com/scylladb/python-driver/pull/180
- PR to cqlsh: https://github.com/scylladb/scylla-tools-java/pull/319

**Comment by Lorak-mmk** [comment]
Reopening because the change was reverted due to a bug in python driver.
