### ISSUE TITLE
system_distributed_everywhere should not be shown in "desc schema"

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-tools-java#318]
"desc schema" doesn't currently show any system* tables
but since 5.0(or earlier? 4.0 definitely didn't have it) it started showing 
```
CREATE KEYSPACE system_distributed_everywhere WITH replication = {'class': 'EverywhereStrategy'}  AND durable_writes = true;

CREATE TABLE system_distributed_everywhere.cdc_generation_descriptions_v2 (
...
```

and I don't think this belongs there.
"desc schema" is used for user tables, system tables have nothing to do there

**Comment by avelanarius** [comment]
The reason of the bug: https://github.com/scylladb/scylla-tools-java/blob/caf754f2434a55ad04e9dd147b8d97c62b8d8427/pylib/cqlshlib/cql3handling.py#L38

`SYSTEM_KEYSPACES` is missing `system_distributed_everywhere`
