### ISSUE TITLE
Upgrade scylla-driver-core from 3.11.2.5 to 3.11.5.1

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-tools-java#343]
https://github.com/scylladb/java-driver/compare/3.11.2.5...3.11.4.0 

Might require updating Netty (which isn't a bad thing by itself) and other libraries while at it.

**Comment by mykaul** [comment]
Some deps are already updated here - https://github.com/scylladb/scylla-tools-java/pull/298 - so perhaps it should come first.

**Comment by mykaul** [comment]
Now 3.11.5.0 is available, even longer diff - https://github.com/scylladb/java-driver/compare/3.11.2.5...3.11.5.0

**Comment by mykaul** [comment]
I reckon it's https://github.com/scylladb/scylla-tools-java/blob/95b3c9dd4095c40729605d650dc1011e192fe93c/build.xml#L465 - unsure where else?

**Comment by yaronkaikov** [comment]
@scylladb/scylla-maint  please backport to `5.4` and `5.2`

**Comment by yaronkaikov** [comment]
@denesb This is also needed together with https://github.com/scylladb/scylla-tools-java/issues/365

**Comment by denesb** [comment]
Backport PRs:
* 5.4 - https://github.com/scylladb/scylladb/pull/16692
* 5.2 - https://github.com/scylladb/scylladb/pull/16693
