### ISSUE TITLE
Old version of libthrift dependency

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla-tools-java#352]
scylla-tools-java (as of https://github.com/scylladb/scylla-tools-java/commit/86a200e324fac3b4a47b7954e30de6e05a4e7ce0) uses libthrift in version 0.9.2. This dependency is flagged by security scanners. The dependency should be updated or the Thrift functionality should be removed from scylla-tools-java (refs https://github.com/scylladb/scylladb/issues/3811).

The fix should be backported to older Scylla versions.

**Comment by avelanarius** [comment]
It's vital to note that Apache Cassandra has decided to not fix ("Won't fix") this problem: https://issues.apache.org/jira/browse/CASSANDRA-15424, even though they still maintain Apache Cassandra 3.x, which uses this old libthrift dependency.

**Comment by mykaul** [comment]
For some reason this did not get backported - @roydahan - can you see it gets where it needs to be?

**Comment by yaronkaikov** [comment]
We need this backported to `2022.2` and `2022.1`, right @mykaul ?

**Comment by mykaul** [comment]
Not critical, but we could backport it.
