### ISSUE TITLE
Old version of `Netty` dependencies

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-tools-java#363]
Scylla-tools-java uses `netty` version `4.1.58.Final`. Those dependencies are flagged by security scanners and should be updated.

![image](https://github.com/scylladb/scylla-tools-java/assets/9914527/94d997b4-8027-41ed-b136-9cb266d26dfb)

**Comment by yaronkaikov** [comment]
@scylladb/Scylla-maint Please backport this to `2022.2` and `2022.1`

**Comment by denesb** [comment]
2022.2 backport PR: https://github.com/scylladb/scylla-enterprise/pull/3768
Doesn't apply to 2022.1, I will need a backport PR.
The backport PR should also include https://github.com/scylladb/scylla-tools-java/issues/364 and optionally https://github.com/scylladb/scylla-tools-java/issues/352.

**Comment by yaronkaikov** [comment]
> 2022.2 backport PR: [scylladb/scylla-enterprise#3768](https://github.com/scylladb/scylla-enterprise/pull/3768) Doesn't apply to 2022.1, I will need a backport PR. The backport PR should also include #364 and optionally #352.

https://github.com/scylladb/scylla-enterprise-tools-java/pull/39
