### ISSUE TITLE
scylla-tools-java deps - update JNA (if we need to)

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-tools-java#371]
https://github.com/scylladb/scylla-tools-java/blob/95b3c9dd4095c40729605d650dc1011e192fe93c/build.xml#L429 is using a too old version. Cassandra has moved to a much newer version (see https://github.com/apache/cassandra/commit/a8b1fb6ae6e934f4ba0a07deb03b6257c7dcb383 ).

**Comment by mykaul** [comment]
The 'if we need to' is that it's unclear if we need it for cassandara-stress or the tools we do use in this repo in Java...

**Comment by mykaul** [comment]
@roydahan - per our discussion today.

**Comment by mykaul** [comment]
@scylladb/scylla-tools-maint  - please backport to both 5.4 and 5.2.

**Comment by denesb** [comment]
Backported to 5.4 and 5.2.
