### ISSUE TITLE
tag naming convention?

### ISSUE THREAD

**Issue by ultrabug** [scylladb/scylla-tools-java#49]
Hi,

Latest tag for 2.0.rc1 release has changed convention with the rest of the scylla repositories with the addition of a **-core** in the tag name `scylla-core-2.0.rc1`

Is is intended to stay like this in the future? I'm asking because it's a bit messy to maintain packaging consistency with tag names changes on release cycles.

Thanks!

**Comment by penberg** [comment]
@ultrabug That looks like a bug in our release scripts. Let me have a look.

**Comment by penberg** [comment]
Fixed. Thanks for reporting, @ultrabug!
