### ISSUE TITLE
Investigate sstableloader slownes in Amos migration experiment

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla-tools-java#62]
In the experiment performed by Amos sstableloader does not perform as well as we would like it to. It would be good to debug the sstableloader running on that enviroment and see what's slowing the migration process down.

**Comment by slivne** [comment]
@slivne we had an email thread about it repost the info

**Comment by amoskong** [comment]
Related Email Subjects:
- Sstableloader test result (1TB)
- Spark Migration Result (1TB)

**Comment by elcallio** [comment]
SStableloader is migrated.
