### ISSUE TITLE
sstabledump return timestamp value from map column with server localtime offset

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-tools-java#82]
sstabledump return timestamp value from map column with server localtime offset.
Example:
```
1. CREATE KEYSPACE ks WITH replication={'class':'SimpleStrategy', 'replication_factor':1}
2. CREATE TABLE testdatatype (a ascii PRIMARY KEY, k timestamp,  r map<timestamp, text>)
3. INSERT INTO testdatatype (a, k, r) values ('ascii', '2005-07-14 12:30:00+0000', {'2005-07-14 12:30:00+0000': '1', '2005-07-14 13:30:00+0000': '2'})
4. SELECT * FROM testdatatype
     a     | k                                                       | r
   -------+-----------------------------------------------+----------------------------------------------------------------------------------
   ascii | 2005-07-14 12:30:00.000000+0000 | {'2005-07-14 12:30:00.000000+0000': '1', '2005-07-14 13:30:00.000000+0000': '2'}
```
When run sstabledump, it's output is:
```
[u'2005-07-14 15:30+0300']
[u'2005-07-14 16:30+0300']
```
To prevent this we need to add to the sstabledump shell script JAVA parameter "-Duser.timezone=UTC"

**Comment by avikivity** [comment]
It's possible to argue that the user prefers the data in local time, but I think UTC is better for everyone.

**Comment by slivne** [comment]
I don't think that we need todo this for the user  if the user want to set this up he can do it in java env locally.

Following the same logic all other tools and code should be moved to UTC but thats not how it works as we all know.

I tried searching cassandra for https://issues.apache.org/jira/issues/?jql=project%20%3D%20CASSANDRA%20AND%20text%20~%20user.timezone and did not find any issue instructing to set this up 

for the tests the correct thing todo is to set the TZ env variable.

**Comment by slivne** [comment]
I sent a pull request to change dtest https://github.com/scylladb/scylla-dtest/pull/817

closing this issue
