### ISSUE TITLE
sstableloader can generate statements with explicit timestamp for counter tables

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla-tools-java#83]
Modifying anything in a counter table with an explicit timestamp (WITH TIMESTAMP = <time>) is disallowed (for some reason). 

We bypass this for counter updates by special treating our wormholed "raw" counter updates. But at the very least we can (apparently) run into (range) tombstones for counter tables, which in turn generates a delete with timestamp. This to goes boom. 

We can sort of handle this by always removing explicit (textual) timestamp for any op on a counter table and rely on the cql options timestamp field instead (which now works in the driver since we are at v3 of wire protocol). However, if we do this we can never do any batch updates for counter tables, since batch statement share the same time stamp field (could potentially group, but very doubtful if this will gain anything).

**Comment by avikivity** [comment]
I think we can allow USING TIMESTAMP for deletes in counter tables.

(the timestamp shouldn't really matter, since you can't resurrect a counter)

**Comment by elcallio** [comment]
Wrong repository! :-) 
Maybe, but breaks compatibility (and what an important compatibility it is!). Also, afaik, it is legal to have non-counter columns in a counter table, no? That means there could be other ops that violate the no timestamp constraint.

**Comment by avikivity** [comment]
Counters are all-or-nothing.

**Comment by avikivity** [comment]
And an extension doesn't violate compatibility

**Comment by pdziepak** [comment]
Timestamps for counter columns are largely irrelevant. Tombstones always wins anyway and merging two live counter cells doesn't involve tombstone comparison. They can be queried though which is the only reason why Scylla internally bothers to propagate them.

I am not sure why `USING TIMESTAMP` with counters is disallowed, it may be a remnant of the times when Cassandra allowed deleting and recreating a counter or a later restriction to make sure that users understand that those timestamps don't mean much.
