### ISSUE TITLE
sstableloader null clustering column gives InvalidQueryException

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla-tools-java#88]
It is (unfortunately) valid to have null/empty clustering values in a row, which manifests itself as empty value clustering prefixes in the cql row reader. 
However, translating this to value=null works poorly with bound/prepared statements, and there is no "clean" way to set an empty value. 

Options are to either exclude the value, which would be valid in the insert case, but not for an update. Or "fake" empty values by simply making the value the empty byte buffer value from sstable, and fake yet another codec into the driver that simply forwards the data raw.

**Comment by elcallio** [comment]
See #57 for original problem, the solution to which uses null values. 
Those null values however do no longer work/do not work for some tables.

**Comment by glommer** [comment]
we can't really skip it either in inserts because that row will have columns of its own, no ?

Can't we just not send a prepared statement in that case, if the problem is with bindings ?

**Comment by elcallio** [comment]
I think it is binding in general that makes the null be really null. 
And no, inserts cannot really skip clustering either, though we could potentially have it unset. 
But I've sent a patch that simply changes the way these values are forwarded, so that we bypass the serialization stuff, and just send the raw data (i.e. "empty value") in the statement, which gives the desired results. 
Could potentially do this more to simplify UDT handling etc, but should really restructure the whole tool first before going there.

**Comment by slivne** [comment]
patch "sstableloader: Use "empty" instead of null in bound values for cluster col"
