### ISSUE TITLE
Selectively copy configuration/property files for cassandra tools 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-tools-java#94]
In https://github.com/scylladb/scylla-tools-java/blob/master/dist/common/cassandra.in.sh#L14 we copy from $SCYLLA_CONF everything 

We have seen cases in which some non expected files are located in this directory and that causes issues - lets make the copy more selective and copy what is needed

**Comment by slivne** [comment]
@amnonh ping

**Comment by tarzanek** [comment]
this caused a regression in nodetool with AMI
https://github.com/scylladb/scylla/issues/5067
